spring.datasource.url: jdbc:${JAWSDB_BROWN_URL:mysql://localhost:3306/site?useSSL=false&serverTimezone=UTC}
spring.datasource.username: root
spring.datasource.password: root
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
server.port: ${PORT:8070}

blog.title: QuietCorner
blog.subtitle: Blog
blog.phone: +7 915 871-59-39
blog.email: s.khoroshkov@mail.ru
blog.copyright: Alternative
blog.copyrightFrom: 2022
spring:
  jpa:
    show-sql: false
    properties: true
  mail:
    host: smtp.yandex.ru
    port: 465
    username: KhoroshkovBlogEngine@yandex.ru
    password: KhoroshkovBlogEngine1
    protocol: smtps

